<?php
// created by duangan, 2015-5-8 -->
// support person deal function.    -->

// 朝代数组
$person = array
(
    array
    (
        // 科学家
        array("爱因斯坦"),
        array("牛顿"),
        array("伦琴"),
        array("洛伦兹"),
        array("塞曼"),
        array("贝可勒尔"),
        array("居里夫人"),
        array("瑞利"),
        array("汤姆孙"),
        array("马可尼"),
        array("巴克拉"),
        array("普朗克"),
        array("玻尔"),
        array("赫兹"),
        array("霍金"),
        array("費曼"),
        array("麦克斯韦"),
        array("法拉第"),
        array("巴斯德"),
        array("伽俐略"),
        array("亚里士多德"),
        array("达尔文"),
        array("欧几里德"),
        array("哥白尼"),
        array("拉瓦锡"),
        array("胡克"),
        array("海森堡"),
        array("弗莱明"),
        array("哈维"),
        array("孟德尔"),
        array("伦琴"),
        array("欧拉"),
        array("开普勒"),
        
        落下闳
        刘徽
        祖冲之
        张子信
        马钧
        array("刘焯"),
        array("巢元方"),
        孙思邈
        王充
        array("蔡伦"),
        array("张衡"),
        array("张仲景"),
        array("华佗"),
        僧一行
        王孝通
        李淳风
        王恂
        韩鄂
        直鲁古
        李春
        沈括
        苏颂
        毕昇
        郭守敬
        王恂
        李冶
        朱世杰
        王祯
        刘完素
        朱思本
        利玛窦
        徐光启
        李之藻
        李时珍
        宋应星
        徐霞客
        方以智
        程大位
        吴有性
        茅元仪
        高一志
        汤若望
        南怀仁
        徐日昇
        张诚
        马礼逊
        王清任
        李善兰
        詹天佑
        陈景润
        袁隆平
        
    ),
    array
    (
        // 文学
        array("荷马"),
        array("莎士比亚"),
        array("薄伽丘"),
        array("易卜生"),
        狄德罗
        
        array("屈原"),
        array("蔡琰"),
        array("蔡邕"),
        array("陈琳"),
        array("孔融"),
        array("谢灵运"),
        array("陶渊明"),
        array("王勃"),
        array("杨炯"),
        array("卢照邻"),
        array("骆宾王"),
        array("王维"),
        array("孟浩然"),
        array("岑参"),
        array("王昌龄"),
        array("李白"),
        array("杜甫"),
        array("白居易"),
        array("元稹"),
        array("韩愈"),
        array("柳宗元"),
        array("刘禹锡"),
        array("李翱"),
        array("李贺"),
        array("李商隐"),
        array("杜牧"),
        array("杜佑"),
        array("刘知几"),
        罗隐
        司空图
        温庭筠
        欧阳炯
        韦庄
        杜光庭
        冯延巳
        苏洵
        苏轼
        苏辙
        欧阳修
        黄庭坚
        辛弃疾
        马远
        夏圭
        元好问
        董解元
        关汉卿
        马致远
        张可久
        乔吉
        白朴
        王实甫
        郑光祖
        array("罗贯中"),
        array("施耐庵"),
        冯梦龙
        凌蒙初
        钱谦益
        张岱
        吴伟业
        袁宗道
        袁宏道
        袁中道
        汤显祖
        龚自珍
        冯桂芬
        李渔
        侯方域
        魏禧
        汪琬
        方苞
        刘大櫆
        蒋士铨
        赵翼
        黄遵宪
        陈三立
        陈衍
        沈曾植
        纳兰性德
        朱彝尊
        陈维崧
        array("曹雪芹"),
        蒲松龄
        吴敬梓
        林纾
        余光中
        鲁迅
        郭沫若
        矛盾
        巴金
        老舍
        叶圣陶
        冰心
        萧红
        张恨水
        朱自清
        张爱玲
        沈从文
        徐志摩
        林微音
        田汉
        夏衍
        丁玲
        郁达夫
        杨逵
        柏杨
        周梦蝶
        李敖
        白先勇
        陈若曦
        琼瑶
        三毛
        龙应台
        邱妙津
        张系国
        王小波
        莫言
        贾平凹
        张艺谋
        
    )
,
    array
    (
        // 艺术体育
        array("达芬奇"),
        array("贝多芬"),
        array("巴赫"),
        array("毕加索"),
        array("米开朗基罗"),
        
        array("曹不兴"),
        array("王羲之"),
        array("顾恺之"),
        array("阎立本"),
        array("阎立德"),
        array("吴道子"),
        array("张萱"),
        array("周昉"),
        array("欧阳询"),
        array("虞世南"),
        array("颜真卿"),
        array("柳公权"),
        array("张旭"),
        array("怀素"),
        李龟年
        公孙大娘
        谢阿蛮
        荆浩
        关仝
        董源
        巨然
        徐熙
        黄筌
        顾闳中
        周文矩
        石恪
        张择端
        张瑀
        王庭筠
        武元直
        李山
        徐渭
        陈洪绶
        沈周
        文征明
        唐寅
        仇英
        董其昌
        王时敏
        王翚
        王鉴
        王原祁
        吴历
        恽寿平
        八大山人
        石涛
        渐江
        髡残
        金农
        郑板桥
        任伯年
        吴昌硕
        居廉
        array("齐白石"),
        林怀民
        周杰伦
        蔡依林
        王菲
        崔健
        李安
        蔡明亮
        杨德昌
        侯孝贤
        魏德圣
        钮承泽
        黄永玉
        王造时
        
        array("刘翔"),
        霍元甲
    ),
    array
    (
        // 人文思想家
        array("柏拉图"),
        array("亚里士多德"),
        array("洛克"),
        array("亚当·斯密"),
        array("奥古斯丁"),
        array("笛卡尔"),
        array("卢梭"),
        array("马尔萨斯"),
        array("培根"),
        array("伏尔泰"),
        array("马基维利亚"),
        array("弗洛伊德"),
        array("马克思"),
        
        array("孔子"),
        array("老子"),
        array("孟子"),
        array("墨子"),
        array("杨朱学派"),
        array("惠施"),
        array("公孙龙"),
        array("邓析子"),
        array("庄子"),
        array("司马迁"),
        array("刘向"),
        array("刘歆"),
        array("申韩"),
        array("郑玄"),
        array("王肃"),
        array("何晏"),
        array("王弼"),
        array("阮籍"),
        array("嵇康"),
        array("裴頠"),
        array("郭象"),
        array("王通"),
        array("郑玄"),
        array("皮日休"),
        array("王溥"),
        array("朱熹"),
        周濂溪
        程颢
        程颐
        王若虚
        陆九龄
        许衡
        刘因
        吴澄
        胡三省
        马端临
        array("王阳明"),
        王艮
        王夫之
        黄宗羲
        顾炎武
        范钦
        袁枚
        唐甄
        方以智
        朱舜水
        颜元
        惠栋
        段玉裁
        王引之
        王念孙
        戴震
        姚鼐
        胡适
        陈独秀
        钱玄同
        储安平
        李大钊
        陶行知
        陈西滢
        王世杰
        梁实秋
        傅斯年
        翁文灏
        蒋廷黻
        王国维
        钱穆
        熊十力
        梁漱溟
        张君劢
        唐君毅
        牟宗三
        徐复观
        季羡林
        顾颉刚
        唐德刚
        蒋梦麟
        朱家骅
        
        array("黄仁宇"),
    ),
    array
    (
        // 宗教人士
        array("耶稣"),
        array("圣保罗"),
        array("摩西"),
        array("马丁·路德"),
        array("加尔文"),
        array("默罕默德"),
        array("释迦摩尼"),
        array("摩尼"),
        
        array("释迦摩尼"),
        array("龙树"),
        array("鸠摩罗什"),
        array("佛图澄"),
        array("道安"),
        array("慧能"),
        array("神秀"),
        array("神会"),
        行思
        怀让
        灵佑
        慧济
        百丈怀海
        希连
        义玄
        文偃
        文益
        曹山本寂
        雪岩满禅师
        
        葛洪
        array("寇谦之"),
        array("谭峭"),
        杜光庭
        吴筠
        彭晓
        谭紫霞
        刘海
        丘处机
        王喆
        刘德仁
        萧抱珍
        李志常
        李居寿
    ),
    array
    (
        // 工商界
        array("古腾堡"),
        array("瓦特"),
        array("莱特兄弟"),
        array("爱迪生"),
        array("贝尔"),
        array("乔布斯"),
        array("盖茨"),
        array("福特"),
    ),
    array
    (
        // 外国政治人物
        array("凯撒"),
        array("亚历山大大帝"),
        array("君士坦丁大帝"),
        array("成吉思汗"),
        array("乌尔班二世"),
        array("欧麦尔"),
        array("阿育王"),
        array("哥伦布"),
        array("达·伽马"),
        array("查理曼"),
        array("塞鲁士大帝"),
        array("克伦威尔"),
        array("华盛顿"),
        array("玻利瓦尔"),
        array("弗朗西斯科·皮扎诺"),
        array("荷南多·科尔特斯"),
        array("伊莎贝拉一世"),
        array("威廉大帝"),
        array("托马斯·杰佛逊"),
        array("彼得大帝"),
        array("伊丽莎白女王一世"),
        array("查士丁尼一世"),
        
        array("列宁"),
        array("斯大林"),
        
        array("希特勒"),
        array("肯尼迪"),
        麦克阿瑟
        杜鲁门
        尼克松
        基辛格
        卡特
        里根
        克林顿
        老布什
        布什
        希拉里
        奥巴马
    ),
    array
    (
        // 中国先秦
        array("鲧"),
        array("禹"),
        array("启"),
        array("太康"),
        array("羿"),
        array("少康"),
        array("杼"),
        array("桀"),
        array("契"),
        array("汤"),
        array("太甲"),
        array("盘庚"),
        array("武丁"),
        array("帝辛"),
        array("武庚"),
        array("箕子"),
        array("微子启"),
        array("季历"),
        array("周文王"),
        array("周武王"),
        array("周公"),
        array("周成王"),
        array("周昭王"),
        array("周穆王"),
        array("周懿王"),
        array("周厉王"),
        array("周宣王"),
        array("周幽王"),
        array("周携王"),
        array("周平王"),
        array("郑庄公"),
        array("齐桓公"),
        array("宋襄公"),
        array("楚成王"),
        array("晋文公"),
        array("秦穆公"),
        array("楚庄王"),
        array("吴王阖闾"),
        array("越王勾践"),
        array("孙武"),
        array("伍子胥"),
        array("西施"),
        array("魏文侯"),
        array("魏成子"),
        array("李悝"),
        array("乐羊"),
        array("吴起"),
        array("西门豹"),
        array("公仲连"),
        array("楚悼王"),
        array("邹忌"),
        array("田忌"),
        array("孙膑"),
        array("申不害"),
        array("商鞅"),
        array("魏惠王"),
        array("齐威王"),
        array("庞涓"),
        array("秦孝公"),
        array("燕昭王"),
        array("赵武灵王"),
        array("田单"),
        array("白起"),
        array("范雎"),
        array("秦昭王"),
        array("廉颇"),
        array("王龁"),
        array("赵括"),
        array("信陵君"),
        array("平原君"),
        array("春申君"),
        array("孟尝君"),
        array("吕不韦"),
        array("乐毅"),
        array("张仪"),
        array("公孙衍"),
        array("李冰"),
        array("韩非子"),
        array("王翦"),
        array("李牧"),
        array("荆轲"),
        array("太子丹"),
        array("王贲"),
        array("项燕"),
    ),
    array
    (
        // 中国秦汉晋南北朝
        array("秦始皇"),
        array("李斯"),
        array("尉缭"),
        array("蒙恬"),
        array("史禄"),
        array("赵佗"),
        array("赵高"),
        array("胡亥"),
        array("章邯"),
        array("项梁"),
        array("项羽"),
        array("陈胜"),
        array("吴广"),
        array("子婴"),
        array("刘邦"),
        array("田荣"),
        array("陈婴"),
        array("英布"),
        array("范增"),
        array("张良"),
        array("萧何"),
        array("韩信"),
        array("英布"),
        array("彭越"),
        array("李左车"),
        array("郦食其"),
        array("蒯通"),
        array("龙且"),
        array("灌婴"),
        array("吕后"),
        array("周勃"),
        array("陈平"),
        array("李广"),
        array("汉文帝"),
        array("汉景帝"),
        array("晁错"),
        array("周亚夫"),
        array("刘濞"),
        array("汉武帝"),
        array("主父偃"),
        array("卫青"),
        array("李陵"),
        array("霍去病"),
        array("董仲舒"),
        array("汉昭帝"),
        array("霍光"),
        array("汉宣帝"),
        array("汉元帝"),
        array("申屠圣"),
        array("徒苏令"),
        array("汉成帝"),
        array("赵飞燕"),
        array("赵过"),
        array("氾胜之"),
        array("孔仅"),
        array("东郭咸阳"),
        array("桑弘羊"),
        array("王凤"),
        array("王莽"),
        array("冒顿单于"),
        array("张骞"),
        array("张汤"),
        array("光武帝"),
        array("窦固"),
        array("窦宪"),
        array("班超"),
        array("汉明帝"),
        array("邓骘"),
        array("汉顺帝"),
        array("梁冀"),
        array("汉桓帝"),
        array("汉灵帝"),
        array("何进"),
        array("袁绍"),
        array("董卓"),
        array("张让"),
        array("汉献帝"),
        array("王允"),
        array("吕布"),
        array("李傕"),
        array("郭汜"),
        array("曹操"),
        array("张既"),
        array("崔实"),
        array("张角"),
        array("孙权"),
        array("刘备"),
        array("刘禅"),
        array("诸葛亮"),
        array("关羽"),
        array("张飞"),
        array("司马昭"),
        array("司马炎"),
        array("刘焉"),
        array("陈寿"),
        array("皇甫嵩"),
        array("卢植"),
        array("朱儁"),
        array("张鲁"),
        array("丁原"),
        array("桥瑁"),
        array("孙坚"),
        array("王允"),
        array("贾诩"),
        array("马腾"),
        array("韩遂"),
        array("刘表"),
        array("张绣"),
        array("张济"),
        array("孙策"),
        array("袁术"),
        array("刘璋"),
        array("公孙瓒"),
        array("陶谦"),
        array("公孙度"),
        array("士燮"),
        array("陈登"),
        array("袁尚"),
        array("袁谭"),
        array("袁熙"),
        array("公孙康"),
        array("周瑜"),
        array("张昭"),
        array("曹仁"),
        array("鲁肃"),
        array("庞统"),
        array("黄忠"),
        array("魏延"),
        array("李严"),
        array("赵云"),
        array("张任"),
        array("马超"),
        array("夏侯渊"),
        array("张郃"),
        array("吕蒙"),
        array("李典"),
        array("陆逊"),
        array("司马懿"),
        array("杨仪"),
        array("姜維"),
        array("顾雍"),
        array("诸葛恪"),
        array("孙亮"),
        array("孙峻"),
        array("锺会"),
        array("邓艾"),
        array("羊祜"),
        array("曹丕"),
        array("曹植"),
        array("陈群"),
        array("法正"),
        array("蒋琬"),
        array("费祎"),
        array("黄皓"),
        array("陆抗"),
        array("顾雍"),
        array("孟获"),
        array("马谡"),
        array("晋惠帝"),
        array("杨骏"),
        array("贾南风"),
        array("司马玮"),
        array("司马伦"),
        array("司马越"),
        array("司马睿"),
        array("王导"),
        array("谢安"),
        array("谢玄"),
        array("谢石"),
        array("王敦"),
        array("苏峻"),
        array("祖逖"),
        array("桓温"),
        array("慕容垂"),
        array("苻坚"),
        array("桓玄"),
        array("王猛"),
        array("刘渊"),
        array("刘聪"),
        array("刘曜"),
        array("拓跋珪"),
        array("拓跋嗣"),
        array("拓跋焘"),
        array("石勒"),
        array("石虎"),
        array("石祗"),
        array("苻洪"),
        array("苻健"),
        array("姚苌"),
        array("李特"),
        array("李雄"),
        array("司马颖"),
        array("王衍"),
        array("张轨"),
        array("拓跋猗卢"),
        array("张宾"),
        array("冉闵"),
        array("慕容皝"),
        array("慕容虔"),
        array("慕容恪"),
        array("慕容泓"),
        array("慕容冲"),
        array("朱序"),
        array("苻融"),
        array("乞伏国仁"),
        array("杨定"),
        array("姚兴"),
        array("赫连勃勃"),
        array("乞伏炽磐"),
        array("王镇恶"),
        array("谯纵"),
        array("秃发乌孤"),
        array("慕容宝"),
        array("刘裕"),
        array("徐羡之"),
        array("檀道济"),
        array("宋文帝"),
        array("萧道成"),
        array("袁粲"),
        array("沈攸之"),
        array("齐武帝"),
        array("萧子良"),
        array("萧鸾"),
        array("萧宝卷"),
        array("萧衍"),
        array("陈霸先"),
        array("王僧辩"),
        array("萧绎"),
        array("陈叔宝"),
        array("崔宏"),
        array("崔浩"),
        array("冯太后"),
        array("杨大眼"),
        array("拓跋宏"),
        array("尔朱荣"),
        array("胡太后"),
        array("高欢"),
        array("高洋"),
        array("窦泰"),
        array("韦孝宽"),
        array("苏绰"),
        array("宇文泰"),
        array("宇文护"),
        array("宇文觉"),
        array("宇文邕"),
        array("赵贵"),
        array("独孤信"),
 ),
    array
    (
        // 中国隋唐五代
        array("杨忠"),
        array("杨坚"),
        array("高颎"),
        array("杨广"),
        array("苏威"),
        array("李德林"),
        array("尉迟迥"),
        array("司马消难"),
        array("韦孝宽"),
        array("王谊"),
        array("贺若弼"),
        array("韩擒虎"),
        array("杨侗"),
        array("杨勇"),
        array("杨素"),
        array("宇文化及"),
        array("李佛子"),
        array("冼夫人"),
        array("宇文恺"),
        array("长孙晟"),
        array("韦云起"),
        array("王薄"),
        array("杨玄感"),
        array("翟让"),
        
        array("李虎"),
        array("李渊"),
        array("李建成"),
        array("李元吉"),
        array("李世民"),
        array("李密"),
        array("王世充"),
        array("刘黑闼"),
        array("窦建德"),
        array("刘武周"),
        array("宋金刚"),
        array("杜伏威"),
        array("辅公祏"),
        array("萧铣"),
        array("房玄龄"),
        array("杜如晦"),
        array("长孙无忌"),
        array("魏徵"),
        array("马周"),
        array("褚遂良"),
        array("高士廉"),
        array("萧瑀"),
        array("尉迟敬德"),
        array("李靖"),
        array("侯君集"),
        array("程知节"),
        array("李世勣"),
        array("秦叔宝"),
        array("薛仁贵"),
        array("李勣"),
        array("苏定方"),
        array("李承乾"),
        array("李泰"),
        array("李治"),
        array("武则天"),
        array("徐敬业"),
        array("狄仁杰"),
        array("张柬之"),
        array("李旦"),
        array("张仁愿"),
        array("姚崇"),
        array("武三思"),
        array("上官婉儿"),
        array("张柬之"),
        array("武三思"),
        array("韦后"),
        array("李隆基"),
        array("太平公主"),
        array("姚崇"),
        array("宋璟"),
        array("卢怀慎"),
        array("张九龄"),
        array("韩休"),
        array("李林甫"),
        array("杨国忠"),
        array("高仙芝"),
        array("哥舒翰"),
        array("安禄山"),
        array("高力士"),
        array("封常清"),
        array("郭子仪"),
        array("颜杲卿"),
        array("史思明"),
        array("李光弼"),
        array("李亨"),
        array("李辅国"),
        array("仆固怀恩"),
        array("安庆绪"),
        array("张巡"),
        array("许远"),
        array("鱼朝恩"),
        array("史朝义"),
        array("李适"),
        array("杨炎"),
        array("刘晏"),
        array("卢杞"),
        array("李宝臣"),
        array("李希烈"),
        array("李晟"),
        array("李怀光"),
        array("裴延龄"),
        array("韦执谊"),
        array("王叔文"),
        array("韩泰"),
        array("李纯"),
        array("杜黄裳"),
        array("吴元济"),
        array("武元衡"),
        array("裴度"),
        array("李愬"),
        array("李祐"),
        array("李光颜"),
        array("王守澄"),
        array("刘克明"),
        array("宋申锡"),
        array("李训"),
        array("郑注"),
        array("仇士良"),
        array("李德裕"),
        array("李吉甫"),
        array("郑覃"),
        array("李宗闵"),
        array("牛僧孺"),
        array("黄巢"),
        array("孙伏伽"),
        array("田令孜"),
        array("崔胤"),
        
        array("李国昌"),
        array("李克用"),
        李存勗
        朱温
        石敬瑭
        array("李茂贞"),
        郭威
        柴荣
        李昪
        秦宗权
        王处直
        王镕
        刘守光
        高季兴
        马殷
        刘隐
        杨行密
        钱镠
        王审知
        曲承裕
        李振
        敬翔
        裴枢
        李克宁
        张承业
        周德威
        朱友珪
        朱友文
        朱友贞
        杨师厚
        张文礼
        王彦章
        李继岌
        王建
        王衍2
        郭崇韬
        李继岌
        李袭吉
        赵在礼
        李绍荣
        李嗣源
        李从荣
        李从厚
        李从珂
        朱弘昭
        冯赟
        孟知祥
        孟昶
        杨光远
        刘知远
        桑维翰
        赵德钧
        杨渥
        钟传
        张颢
        徐温
        杨隆演
        徐知训
        朱瑾
        杨溥
        李璟
        王潮
        王审知
        王延曦
        王延政
        李仁达
        留从效
        边镐
        刘言
        李弘冀
        李景遂
        李煜
        高从诲
        孙儒
        马希范
        马希广
        马希萼
        马光惠
        马希崇
        刘言
        王逵
        潘叔嗣
        周行逢
        刘䶮
        刘玢
        张遇贤
        刘晟
        刘鋹
        桑维翰
        吴峦
        杜重威
        李守贞
        范廷光
        张从宾
        石重信
        石重乂
        侯益
        安重荣
        冯道
        景延广
        石重贵
        冯玉
        张彦泽
        高行周
        慕容彦超
        杨邠
        史弘肇
        王章
        魏仁浦
        柴荣
        刘崇
        杨衮
        柴宗训
        钱弘佐
        钱俶
   
        
    ),
    array
    (
        // 中国宋辽夏金元
        赵匡胤
        赵普
        范质
        赵光义
        王全斌
        崔彦进
        刘光义
        曹彬
        花蕊夫人
        刘鋹
        龚澄枢
        卢琼仙
        潘美
        李从善
        潘佑
        林仁肇
        曹彬
        陈洪进
        刘继元
        朱全赟
        杨业
        王小波
        李顺
        赵德昭
        赵德芳
        赵廷美
        赵元佐
        赵元僖
        赵元恒
        王继恩
        吕端
        寇准
        萧挞凛
        王钦若
        王旦
        赵祯
        范仲淹
        吕夷简
        富弼
        包拯
        韩琦
        狄青
        侬智高
        赵曙
        宋神宗
        王安石
        司马光
        郑侠
        吕惠卿
        曾布
        李定
        蔡京
        赵煦
        高太后
        赵佶
        宋江
        方腊
        韩世忠
        蔡京
        李纲
        张邦昌
        钦宗
        刘豫
        杨继业
        徐禧
        李舜举
        李稷
        高永能
        
        耶律阿保机
        韩延徽
        韩知古
        康默记
        卢文进
        述律平
        耶律德光
        耶律倍
        耶律阮
        耶律屋质
        耶律察割
        耶律璟
        耶律娄国
        耶律敌烈
        耶律李胡
        王洪
        耶律喜隐
        耶律贤
        室昉
        郭袭
        萧绰
        耶律斜轸
        韩德让
        耶律休哥
        辽圣宗
        耶律宗真
        萧耨斤
        耶律宗元
        耶律洪基
        张俭
        萧惠
        萧特末
        富弼
        耶律乙辛
        萧观音
        耶律濬
        耶律延禧
        耶律淳
        耶律大石
        萧塔不烟
        耶律夷列
        耶律普速完
        屈出律
        李处温
        萧干
        童贯
        天祚帝
        耶律楚材
        
        完颜阿骨打
        完颜娄室
        完颜宗望
        完颜吴乞买
        金世宗
        金章宗
        完颜永济
        金宣宗
        勃极烈完颜斜
        完颜宗翰
        完颜宗弼
        金熙宗
        完颜亮
        仆散忠义
        完颜璟
        李师儿
        吴曦
        仆散揆
        完颜承裕
        徒单镒
        耶律留哥
        胡沙虎
        完颜珣
        术虎高琪
        金兀术
        完颜陈和尚
        张惠
        
        
        李彝超
        李彝殷
        李继捧
        李继迁
        李继隆
        李德明
        李元昊
        夜落隔通顺
        折逋游龙钵
        曹贤顺
        范雍
        刘平
        石元孙
        夏竦
        任福
        陈执中
        景泰
        种世衡
        李谅祚
        野利旺荣
        李宁林格
        野利皇后
        梁乙埋
        景询
        梁太后
        嵬名浪遇
        王韶
        种谔
        李宪
        徐禧
        梁乞逋
        章楶
        夏崇宗
        小梁太后
        种师道
        刘法
        刘仲武
        夏仁宗
        任得敬
        李察哥
        李仁友
        罗太后
        夏襄宗
        李承祯
        李遵顼
        李德旺
        嵬名令公
        李德任
        李睍
        
        
        宋高宗
        秦桧
        岳飞
        韩世忠
        张浚
        刘锜
        赵鼎
        李光
        胡铨
        陈康伯
        李宝
        虞允文
        刘琦
        杨存中
        赵昚
        张浚
        周必大
        赵惇
        韩侂胄
        史弥远
        赵汝愚
        赵扩
        史弥远
        宋理宗
        丁大全
        贾似道
        真德秀
        赵范
        孟珙
        余玠
        赵葵
        杜杲
        曹友闻
        张钰
        向士璧
        曹世雄
        贾似道
        丁大全
        宋度宗
        郝经
        吕文德
        吕文焕
        范文虎
        李庭芝
        张顺
        张贵
        宋恭帝
        赵卯发
        唐震
        江万里
        谢太后
        张世杰
        文天祥
        李芾
        陆秀夫
        张弘范
        
        合不勒
        胡沙虎
        俺巴孩
        也速该
        札木合
        王罕
        铁木真
        蒙哥
        窝阔台
        忽必烈
        木华黎
        孛鲁
        察罕
        术赤
        合撒儿
        拖雷
        拔都
        阿里不哥
        察合台
        旭烈兀
        贵由
        旭烈兀
        兀良哈台
        阿速台
        玉龙答失
        海都
        刘中
        铁穆尔
        伯颜
        玉昔帖木儿
        阿忽台
        元仁宗
        铁木迭儿
        燕帖木儿
        脱脱
        贾鲁
        察罕帖木儿
        李思齐
        扩廓帖木儿
        纳哈出
        刘益
        把匝剌瓦尔密
        天元帝
        也速迭尔
        鬼力赤
        坤帖木儿
        刘秉忠
        许衡
        姚枢
        史天泽
        李全
        李璮
        杨妙真
        阿难答
        马可波罗
    ),
    array
    (
        // 中国明清
        彭和尚
        周子旺
        韩山童
        刘福通
        韩林儿
        郭子兴
        彭莹玉
        邹普胜
        徐寿辉
        张士诚
        陈友谅
        明玉珍
        郭子兴
        朱元璋
        徐达
        常遇春
        冯胜
        傅友德
        蓝玉
        汤和
        明玉珍
        刘伯温
        朱升
        胡惟庸
        廖永忠
        朱亮祖
        李善长
        郭桓
        耿炳文
        朱标
        朱允炆
        齐泰
        方孝孺
        黄子澄
        姚广孝
        朱樉
        朱㭎
        朱权
        朱棣
        亦失哈
        郑和
        陈子鲁
        刘大夏
        项忠
        明仁宗
        杨士奇
        杨荣
        杨溥
        明宣宗
        王振
        也先
        于谦
        明景帝
        朱见济
        朱见深
        万贵妃
        石亨
        徐有贞
        王文
        曹吉祥
        李贤
        汪直
        梁芳
        朱祐樘
        朱厚照
        刘瑾
        谷大用
        朱寘鐇
        朱宸濠
        朱厚熜
        杨廷和
        毛澄
        张璁
        杨金英
        严嵩
        严世蕃
        徐阶
        俺答
        仇鸾
        朱纨
        张经
        汪直
        胡宗宪
        俞大猷
        朱载垕
        高拱
        海瑞
        张居正
        冯保
        王崇古
        方逢时
        刘显
        殷正茂
        凌云翼
        张佳胤
        潘季驯
        朱常洛
        朱常洵
        郑贵妃
        顾宪成
        孙鑨
        李世达
        赵南星
        杨应龙
        李可灼
        李选侍
        杨涟
        左光斗
        朱由校
        客氏
        魏忠贤
        朱由检
        袁崇焕
        李如松
        孙承宗
        高第
        赵率教
        祖大寿
        王化贞
        王在晋
        左光斗
        王象乾
        满桂
        高见
        贺谦
        马世龙
        王世钦
        杨涟
        魏大中
        袁化中
        熊廷弼
        何可纲
        王之臣
        毛文龙
        孙国桢
        陈继盛

        王自用
        高迎祥
        李自成
        张献忠
        吴三桂
        朱由崧
        朱以海
        朱聿键
        绍武帝
        永历帝
        郑芝龙
        郑成功
        马士英
        高杰
        黄得功
        刘泽清
        刘良佐
        史可法
        张名振
        张煌言
        苏观生
        瞿式耜
        李定国
        孙可望
        金声桓
        耿献忠
        杨有光
        郝永忠
        刘体纯
        刘文秀
        白文选
        袁宗弟
        李来亨
        王光兴
        谭文
        谭诣
        谭宏
        李赤心
        高必正
        何腾蛟
        刘体纯
        郑经
        郑克塽
        左良玉
        
        阿哈出
        猛哥帖木儿
        凡察
        董山
        觉昌安
        塔克世
        努尔哈赤
        皇太极
        豪格
        多铎
        阿敏
        莽古尔泰
        代善
        孝庄皇后
        多尔衮
        杨镐
        林丹汗
        阿济格
        范文程
        宁完我
        孔有德
        孙之獬
        李成梁
        李成栋
        洪承畴
        李国英
        董学礼
        王一正
        施琅
        耿仲明
        耿精忠
        尚可喜
        尚之信
        顺治
        左懋第
        孝庄太皇太后
        康熙
        索尼
        遏必隆
        苏克萨哈
        鳌拜
        王辅臣
        孙延龄
        吴世璠
        靳辅
        于成龙
        曹寅
        李熙
        噶尔丹
        萨布素
        桑结嘉错
        雍正
        隆科多
        年羹尧
        岳锺琪
        鄂尔泰
        张廷玉
        傅尔丹
        田文镜
        李卫
        乾隆
        array("和珅"),
        戴名世
        班第
        兆惠
        大小和卓
        富德
        福康安
        海兰察
        张广泗
        阿桂
        王三槐
        林爽文
    ),
    array
    (
        // 中国晚晴民国
        
        嘉庆
        马戛尔尼
        道光
        曹振镛
        穆彰阿
        奕山
        陶澍
        林则徐
        魏源
        郑复光
        耆英
        咸丰
        洪秀全
        杜文秀
        马如龙
        曾国藩
        左宗棠
        李鸿章
        胡林翼
        曾国荃
        江忠源
        罗泽南
        同治
        肃顺
        奕䜣
        慈禧太后
        唐绍仪
        邹容
        僧格林沁
        岑毓英
        光绪
        曾纪泽
        康有为
        梁启超
        谭嗣同
        康有溥
        沈葆祯
        张之洞
        丁日昌
        刘坤一
        奕劻
        袁世凯
        载沣
        宣统
        
        array("孙中山"),
        array("黄兴"),
        array("蒋介石"),
        黎元洪
        宋教仁
        汪精卫
        冯玉祥
        阎锡山
        张作霖
        张学良
        莫德惠
        张謇
        溥仪
        陈公博
        陆皓东
        陈少白
        宋庆龄
        宋美龄
        陈少白
        杨度
        蔡元培
        章炳麟
        吴敬恒
        张继
        徐锡麟
        胡汉民
        伍廷芳
        唐绍仪
        王宠惠
        宋嘉树
        戴季陶
        赵秉钧
        陈其美
        李烈钧
        柏文蔚
        谭人凤
        陈炯明
        张勋
        伍廷芳
        程璧光
        朱庆澜
        段祺瑞
        廖仲恺
        越飞
        鲍罗廷
        朱培德
        谭延恺
        卢永祥
        曹锟
        头山满
        熊克武
        孙科
        蔡锷
        唐继尧
        冯国璋
        徐世昌
        许崇智
        吴佩孚
        唐生智
        李宗仁
        白崇禧
        李济深
        陈仪
        马歇尔
        胡宗南
        孙立人
        张自忠
        廖耀湘
        黄百韬
        黄维
        杜聿明
        傅作义
        徐树铮
        王揖唐
        段芝贵
        孙传芳
        陆荣廷
        龙济光
        顾品珍
        张开儒
        龙云
        张怀芝
        陈树藩
        卢永祥
        齐燮元
        王占元
        李纯
        陈光远
        张宗昌
        郭松龄
        赵恒惕
        陈济棠
        刘显世
        王家烈
        谭延闿
        赵恒惕
        何键
        刘湘
        邓锡侯
        杨森
        刘文辉
        韩复榘
        刘镇华
        杨虎城
        郭坚
        党玉琨
        马鸿宾
        马鸿逵
        马麒
        马麟
        马步芳
        马步青
        马仲英
        杨增新
        金树仁
        盛世才
        
        array("毛泽东"),
        array("邓小平"),
        array("周恩来"),
        项英
        张国焘
        张闻天
        朱德
        李济深
        张澜
        高岗
        林伯渠
        林彪
        刘少奇
        彭德怀
        林立果
        华国锋
        
    ),
    array
    (
        // 中国现代
        蒋经国
        李登辉
        严家淦
        array("马英九"),
        连战
        宋楚瑜
        陈水扁
        吴敦义
        游锡堃
        雷震
        蔡英文
        
        胡耀邦
        赵紫阳
        江泽民
        胡锦涛
        温家宝
        习近平
        王岐山
    ),
    array
    (
        // other
    )
);

// 返回大时期的名称
function get_big_person_name($index)
{
    switch($index)
    {
        case 1:
            return "科学";
        case 2:
            return "文学";
        case 3:
            return "艺术体育";
        case 4:
            return "人文思想";
        case 5:
            return "宗教";
        case 6:
            return "工商界";
        case 7:
            return "政治人物";
        case 8:
            return "中国先秦";
        case 9:
            return "中国秦汉晋南北朝";
        case 10:
            return "中国隋唐五代";
        case 11:
            return "中国宋辽夏金元";
        case 12:
            return "中国明清";
        case 13:
            return "中国晚晴民国";
        case 14:
            return "中国现代";
        default:
            return "其它";
    }
}

// 获取 big id begin
function get_big_person_begin()
{
    return 1;   // 从1开始方便通过 GET 传递.
}

// 获取 big id end
function get_big_person_end()
{
    global $person;
    return count($person);
}

// 获取 small id begin
function get_small_person_begin($big_id)
{
    return 1;
}

// 获取 small id end.
function get_small_person_end($big_id)
{
    global $person;
    return count($person[$big_id - 1]);
}

// 获取朝代名称
function get_person_name($big_id, $small_id)
{
    global $person;
    return $person[$big_id - 1][$small_id - 1][0];
}

// 获取是否存在. =1 表示存在； =0表示不存在。
function person_tag_is_exist($tag_name)
{
    for ($ii = get_big_person_begin(); $ii <= get_big_person_end(); $ii++)
    {
        for ($jj = get_small_person_begin($ii); $jj <= get_small_person_end($ii); $jj++)
        {
            if(get_person_name($ii, $jj) == $tag_name)
            {
                return 1;
            }
        }
    }
    
    return 0;
}


?>