<?php
// created by duangan, 2015-5-6 -->
// support key thing deal function.    -->

$key_thing_big = array
(
    "中国古代",
    "中国近现代",
    "世界古代",
    "世界近现代",
    "社会热点",
    "其它"
);

// 关键事件数组
$key_thing = array
(
    array
    (
        // 中国古代
        array("大禹治水"),
        array("诸子百家"),
        array("春秋五霸"),
        array("诸侯变法"),
        array("统一六国"),
        array("焚书坑儒"),
        array("陈胜吴广起义"),
        array("楚汉相争"),
        array("七王之乱"),
        array("汉武帝开西域"),
        array("党锢之祸"),
        array("昆阳之战"),
        array("黄巾军起义"),
        array("官渡之战"),
        array("赤壁之战"),
        array("八王之乱"),
        array("永嘉之祸"),
        array("冉魏灭胡"),
        array("淝水之战"),
        array("参合陂之战"),
        array("侯景之乱"),
        array("三武灭佛"),
        
        array("玄武门之变"),
        array("贞观之治"),
        array("武周代唐"),
        array("怛罗斯战役"),
        array("安史之乱"),
        array("牛李党争"),
        array("唐代藩镇"),
        array("甘露之变"),
        array("黄巢起义"),
        array("白马之祸"),
        array("陈桥兵变"),
        array("高梁河之战"),
        array("杯酒释兵权"),
        array("澶渊之盟"),
        array("庆历新政"),
        array("王安石变法"),
        array("卡特万之战"),
        array("靖康之难"),
        array("绍兴和议"),
        array("蒙古三次西征"),
        array("元灭宋"),
        array("明灭元"),
        array("靖难之变"),
        array("土木堡之变"),
        array("夺门之变"),
        array("张居正变法"),
        array("灭倭寇"),
        array("东林党"),
        array("辽东抗清"),
        array("清灭明"),
        
    ),
    array
    (
        // 中国近现代
        array("利玛窦规矩"),
        array("鸦片战争"),
        array("太平天国"),
        array("湘军"),
        array("甲午战争"),
        array("百日维新"),
        array("义和团"),
        array("东南自保"),
        array("清末新政"),
        array("辛亥革命"),
        array("护法运动"),
        array("二次革命"),
        array("北伐"),
        array("五次反围剿"),
        array("西安事变"),
        array("抗日战争"),
        array("南京大屠杀"),
        array("重庆谈判"),
        array("延安整风运动"),
        array("制宪国民大会"),
        array("解放战争"),
        array("二二八事件"),
        array("朝鲜战争"),
        array("三反五反"),
        array("土地改革"),
        array("反右派"),
        array("大饥荒"),
        array("文化大革命"),
        array("改革开放"),
        array("台湾十大建设"),
        array("美丽岛事件"),
        array("辜汪会谈"),
        array("中国国民党"),
        array("中国共产党"),
        array("民主进步党"),
    ),
    array
    (
        // 世界古代
        array("两河流域-发现农业"),
        array("埃及建国"),
        array("希腊理性之光"),
        array("罗马帝国"),
        array("蛮族入侵"),
        array("基督教兴起"),
        array("神圣罗马帝国"),
        array("十字军东征"),
        array("伊斯兰教兴起"),
        array("奥斯曼帝国"),
        array("地中海城市帝国"),
        array("英国大宪章"),
        array("欧洲黑死病"),
        array("文艺复兴"),
        array("科技革命"),
        array("启蒙运动"),
        array("英国革命"),
        array("美国革命"),
        array("法国革命"),
        array("拿破仑帝国"),
        array("德国统一"),
        array("俄罗斯改革"),
        array("拉美独立浪潮"),
        array("美国南北战争"),
    ),
    array
    (
        // 世界近现代
        array("第一次世界大战"),
        array("十月革命"),
        array("斯大林大清洗"),
        array("1933年经济危机"),
        array("第二次世界大战"),
        array("印度独立"),
        array("非洲独立浪潮"),
        array("登上月球"),
        array("两伊战争"),
        array("海湾战争"),
        array("苏联解体"),
        array("香港回归"),
        array("九一一事件"),
        array("阿富汗战争"),
        array("伊拉克战争"),
    ),
    array
    (
        // 社会热点
        array(""),
        array(""),
        array(""),
    ),
    array
    (
        // other
    )
);

?>