<?php
// created by duangan, 2015-5-6 -->
// support city deal function.    -->

$city_big = array
(
    "全球性都市",
    "外国一线",
    "中国东北",
    "中国华北",
    "中国华东",
    "中国中部",
    "中国南部",
    "中国西部",
    "其它"
);

// 朝代数组
$city = array
(
    array
    (
        // 全球性都市
        array("巴黎"),
        array("伦敦"),
        array("柏林"),
        array("罗马"),
        array("威尼斯"),
        array("维也纳"),
        array("莫斯科"),
        array("新加坡"),
        array("东京"),
        array("悉尼"),
        array("孟买"),
        array("纽约"),
        array("洛杉矶"),
        array("芝加哥"),
    ),
    array
    (
        // 外国一线
        array("阿姆斯特丹"),
        array("布鲁塞尔"),
        array("都柏林"),
        array("利物浦"),
        array("布拉格"),
        array("日内瓦"),
        array("马赛"),
        array("马德里"),
        array("里斯本"),
        array("米兰"),
        array("贝尔格莱德"),
        array("萨拉热窝"),
        array("哥本哈根"),
        array("华沙"),
        array("奥斯陆"),
        array("斯德哥尔摩"),
        array("雅典"),  
        array("赫尔辛基"),
        array("圣彼得堡"),
        array("基辅"),
        array("第比利斯"),
        array("安卡拉"),
        array("伊斯坦布尔"),
        array("耶路撒冷"),
        array("大马士革"),
        array("开罗"),
        array("巴格达"),
        array("德黑兰"),
        array("坎布尔"),
        array("新德里"),
        array("加德满都"),
        array("曼谷"),
        array("吉隆坡"),
        array("雅加达"),
        array("平壤"),
        array("首尔"),
        array("济州"),
        array("大阪"),
        array("北海道"),
        array("京都"),
        array("马尼拉"),
        array("渥太华"),
        array("魁北克"),
        array("西雅图"),
        array("波士顿"),
        array("亚特兰大"),
        array("休斯顿"),
        array("墨西哥城"),
        array("哈瓦那"),
        array("巴拿马城"),
        array("里约"),
        array("海参崴"),
    ),
    array
    (
        // 中国东北
        array("沈阳", "super", "multe-key", "沈阳", "盛京", "奉天"),
        array("哈尔滨"),
        array("长春"),
        array("大连"),
        array("黑河"),
        array("满洲里"),
        array("齐齐哈尔"),
        array("伊春"),
        array("佳木斯"),
        array("大庆"),
        array("牡丹江"),
        array("鸡西"),
        array("海拉尔"),
        array("白城"),
        array("四平"),
        array("吉林"),
        array("通化"),
        array("延吉"),
        array("锦州"),
        array("鞍山"),
        array("丹东"),
        array("阜新"),
        array("通辽"),
        array("赤峰"),
        array("二连浩特"),
    ),
    array
    (
        // 中国华北
        array("北京", "super", "multe-key", "北京", "燕京", "涿郡", "幽州", "北平"), // "大都"歧义太多.
        array("天津"),
        array("石家庄"),
        array("太原"),
        array("济南"),
        array("呼和浩特"),
        array("青岛"),
        array("唐山"),
        array("秦皇岛"),
        array("承德"),
        array("张家口"),
        array("保定"),
        array("邯郸"),
        array("大同"),
        array("临汾"),
        array("包头"),
        array("集宁"),
        array("德州"),
        array("淄博"),
        array("烟台"),
        array("潍坊"),
        array("威海"),
        array("济宁"),
        array("临沂"),
    ),
    array
    (
        // 中国华东
        array("上海", "super", "multe-key", "上海"),
        array("南京", "super", "multe-key", "南京", "金陵", "建康", "江宁", "石头城"),
        array("杭州", "normal", "multe-key", "杭州", "临安", "武林", "余杭", "杭城"),
        array("苏州", "normal", "multe-key", "苏州", "姑苏", "吴都", "吴中", "吴郡", "平江", "吴门"),
        array("扬州", "normal", "multe-key", "扬州", "邗江", "广陵", "江都", "维扬"),
        array("宁波"),
        array("徐州"),
        array("温州"),
        array("合肥"),
        array("安庆"),
        array("无锡"),
        array("常州"),
        array("南通"),
        array("淮安"),
        array("盐城"),
        array("镇江"),
        array("徽州"),
        array("嘉兴"),
        array("湖州"),
        array("绍兴", "normal", "multe-key", "会稽"),
        array("金华"),
        array("衢州"),
        array("台州"),
        array("淮南"),
        array("铜陵"),
        array("滁州"),
        array("巢湖"),
        array("亳州"),
        array("宿州"),
        array("阜阳"),
        array("蚌埠"),
        array("芜湖"),
        array("连云港"),
        array("淮阴"),
    ),
    array
    (
        // 中国中部
        array("西安", "super", "multe-key", "西安", "长安", "镐京", "西京", "大兴城"),
        array("武汉", "super", "multe-key", "武汉", "武昌", "汉口", "汉阳"),
        array("郑州", "super", "multe-key", "郑州"),
        array("开封", "super", "multe-key", "开封", "汴梁", "汴州", "汴京", "大梁"), // "东京"歧义太多.
        array("洛阳"),
        array("长沙", "super", "multe-key", "长沙"),
        array("重庆", "super", "multe-key", "重庆"),
        array("成都", "super", "multe-key", "成都"),
        array("安阳"),
        array("榆林"),
        array("延安"),
        array("铜川"),
        array("宝鸡"),
        array("汉中"),
        array("安康"),
        array("三门峡"),
        array("南阳"),
        array("漯河"),
        array("信阳"),
        array("十堰"),
        array("襄樊"),
        array("宜昌"),
        array("恩施"),
        array("黄石"),
        array("黄冈"),
        array("鄂州"),
        array("岳阳"),
        array("常德"),
        array("株洲"),
        array("邵阳"),
        array("衡阳"),
        array("九江"),
        array("南昌"),
        array("湘潭"),
        array("怀化"),
        array("上饶"),
        array("鹰潭"),
        array("吉安"),
        array("赣州"),
        array("万县"),
        array("绵阳"),
        array("广安"),
        array("巴中"),
        array("咸阳"),
        array("渭南"),
        array("南充"),
        array("都江堰"),
        array("宜宾"),
        array("攀枝花"),
    ),
    array
    (
        // 中国南部
        array("广州", "super", "multe-key", "广州", "番禺", "任嚣城"),
        array("深圳", "super", "multe-key", "深圳"),
        array("澳门"),
        array("韶关"),
        array("东莞"),
        array("佛山"),
        array("南平"),
        array("海口"),
        array("三亚"),
        array("台北", "super", "multe-key", "台北"),
        array("高雄", "super", "multe-key", "高雄"),
        array("台南"),
        array("厦门", "super", "multe-key", "厦门"),
        array("福州"),
        array("汕头"),
        array("茂名"),
        array("莆田"),
        array("三明"),
        array("梅州"),
        array("龙岩"),
        array("宁德"),
        array("潮州"),
    ),
    array
    (
        // 中国西部
        array("兰州"),
        array("乌鲁木齐"),
        array("银川"),
        array("天水"),
        array("武威"),
        array("张掖"),
        array("酒泉"),
        array("陇南"),
        array("固原"),
        array("嘉峪关"),
        array("敦煌"),
        array("玉门"),
        array("西宁"),
        array("海东"),
        array("格尔木"),
        array("玉树"),
        array("哈密"),
        array("库尔勒"),
        array("喀什"),
        array("吐鲁番"),
        array("阿克苏"),
        array("和田"),
        array("阿勒泰"),
        array("伊宁"),
        array("若羌"),
        array("且末"),
        array("库车"),
        array("塔城"),
        array("克拉玛依"),
        array("民丰"),
        array("拉萨"),
        array("昌都"),
        array("昆明"),
        array("个旧"),
        array("丽江"),
        array("普洱"),
        array("大理"),
        array("东川"),
        array("贵阳"),
        array("安顺"),
        array("遵义"),
        array("铜仁"),
        array("南宁"),
        array("桂林"),
        array("柳州"),
        array("百色"),
    ),
    array
    (
        // other
    )
);

?>