<?php
// created by duangan, 2015-5-8 -->
// support person deal function.    -->

$person_big = array
(
    "科学人文宗教",
    "工商人物",
    "外国政治人物",
    "中国远古",
    "中国古代",
    "晚清民国",
    "现代人物",
    "其它"
);


// 人物数组
$person = array
(
    array
    (
        // 科学家
        array("爱因斯坦"),
        array("牛顿"),
        array("伦琴"),
        array("洛伦兹"),
        array("居里夫人"),
        array("普朗克"),
        array("玻尔"),
        array("赫兹"),
        array("霍金"),
        array("麦克斯韦"),
        array("法拉第"),
        array("巴斯德"),
        array("伽利略"),
        array("毕达哥拉斯"),
        array("阿那克西曼德"),
        array("泰勒斯"),
        array("达尔文"),
        array("欧几里德"),
        array("哥白尼"),
        array("拉瓦锡"),
        array("胡克"),
        array("海森堡"),
        array("弗莱明"),
        array("哈维"),
        array("孟德尔"),
        array("欧拉"),
        array("开普勒"),
        array("冯·布劳恩"),
        
        array("祖冲之"),
        array("孙思邈"),
        array("王充"),
        array("蔡伦"),
        array("张衡"),
        array("张仲景"),
        array("华佗"),
        array("僧一行"),
        array("沈括"),
        array("毕昇"),
        array("郭守敬"),
        array("利玛窦"),
        array("徐光启"),
        array("李时珍"),
        array("宋应星"),
        array("徐霞客"),
        array("汤若望"),
        array("南怀仁"),
        array("郑复光"),
        array("马礼逊"),
        array("王清任"),
        array("李善兰"),
        array("詹天佑"),
        array("陈景润"),
        array("李四光"),
        array("梁思成"),
        array("华罗庚"),
        array("袁隆平"),
        
        // 人文思想家
        array("柏拉图"),
        array("亚里士多德"),
        array("阿奎那"),
        array("奥古斯丁"),
        array("培根"),
        array("洛克"),
        array("斯密"),
        array("笛卡尔"),
        array("卢梭"),
        array("伏尔泰"),
        array("斯宾诺莎"),
        array("莱布尼兹"),
        array("休谟"),
        array("康德"),
        array("叔本华"),
        array("黑格尔"),
        array("弗洛伊德"),
        array("荣格"),
        array("马克思"),
        array("恩格斯"),
        array("尼采"),
        array("胡塞尔"),
        array("海德拉尔"),
        array("萨特"),
        array("罗素"),
        array("维特根斯坦"),
        
        array("孔子"),
        array("老子"),
        array("孟子"),
        array("墨子"),
        array("荀子"),
        array("惠施"),
        array("公孙龙"),
        array("邓析子"),
        array("庄子"),
        array("邹忌"),
        array("申不害"),
        array("商鞅"),
        array("韩非子"),
        
        array("司马迁"),
        array("刘向"),
        array("刘歆"),
        array("郑玄"),
        array("阮籍"),
        array("嵇康"),
        array("朱熹"),
        array("周濂溪"),
        array("程颢"),
        array("程颐"),
        array("王若虚"),
        array("陆九龄"),
        array("许衡"),
        array("王阳明"),
        array("王艮"),
        array("王夫之"),
        array("黄宗羲"),
        array("顾炎武"),
        array("袁枚"),
        array("朱舜水"),
        array("段玉裁"),
        array("方苞"),
        array("赵翼"),
        array("王念孙"),
        array("戴震"),
        array("姚鼐"),
        
        array("康有为"),
        array("梁启超"),
        array("章太炎"),
        array("胡适"),
        array("陈独秀"),
        array("储安平"),
        array("李大钊"),
        array("陶行知"),
        array("梁实秋"),
        array("傅斯年"),
        array("蒋廷黻"),
        array("王国维"),
        array("钱穆"),
        array("严耕望"),
        array("余英时"),
        array("熊十力"),
        array("梁漱溟"),
        array("季羡林"),
        array("顾颉刚"),
        array("唐德刚"),
        array("蒋梦麟"),
        array("朱家骅"),
        array("费正清"),
        array("黄仁宇"),
        array("侯外庐"),


        // 宗教人士
        array("耶稣"),
        array("圣保罗"),
        array("摩西"),
        array("马丁·路德"),
        array("加尔文"),
        array("摩尼"),
        array("高一志"),
        array("乌尔班二世"),
        
        array("穆罕默德"),
        array("哈里发"),
        array("马坚"),
        
        array("释迦牟尼"),
        array("龙树"),
        array("鸠摩罗什"),
        array("佛图澄"),
        array("道安"),
        array("慧能"),
        array("神秀"),
        array("神会"),
        array("行思"),
        array("怀让"),
        array("玄奘"),
        array("鉴真"),
 
         // 文学
        array("荷马"),
        array("莎士比亚"),
        array("但丁"),
        array("薄伽丘"),
        array("易卜生"),
        array("莫里哀"),
        array("司汤达"),
        array("巴尔扎克"),
        array("雨果"),
        array("福楼拜"),
        array("莫泊桑"),
        array("大仲马"),
        array("罗曼·罗兰"),
        array("狄更斯"),
        array("勃朗特"),
        array("安徒生"),
        array("普希金"),
        array("陀思妥耶夫斯基"),
        array("托尔斯泰"),
        array("契诃夫"),
        array("狄德罗"),
        array("歌德"),
        array("马尔克斯"),
        array("贝克特"),
        array("宫崎骏"),
        
        array("凡尔纳"),
        array("威尔斯"),
        array("阿西莫夫"),
        array("田中芳树"),
        array("海因莱因"),
        array("克拉克"),
        
        array("屈原"),
        array("孔融"),
        array("谢灵运"),
        array("陶渊明"),
        array("王勃"),
        array("杨炯"),
        array("卢照邻"),
        array("骆宾王"),
        array("王维"),
        array("孟浩然"),
        array("岑参"),
        array("王昌龄"),
        array("李白"),
        array("杜甫"),
        array("白居易"),
        array("元稹"),
        array("韩愈"),
        array("柳宗元"),
        array("刘禹锡"),
        array("李贺"),
        array("李商隐"),
        array("杜牧"),
        array("杜佑"),
        array("刘知几"),
        array("温庭筠"),
        array("韦庄"),
        array("苏洵"),
        array("苏东波", "super", "multe-key", "苏东波", "苏轼"),
        array("苏辙"),
        array("欧阳修"),
        array("黄庭坚"),
        array("辛弃疾"),
        array("元好问"),
        array("关汉卿"),
        array("马致远"),
        array("罗贯中"),
        array("施耐庵"),
        array("冯梦龙"),
        array("袁宗道"),
        array("袁宏道"),
        array("袁中道"),
        array("汤显祖"),
        array("龚自珍"),
        array("冯桂芬"),
        array("黄遵宪"),
        array("陈三立"),
        array("陈衍"),
        array("纳兰性德"),
        array("曹雪芹"),
        array("蒲松龄"),
        array("吴敬梓"),
        array("林纾"),
        array("余光中"),
        array("鲁迅"),
        array("郭沫若"),
        array("矛盾"),
        array("巴金"),
        array("老舍"),
        array("叶圣陶"),
        array("冰心"),
        array("萧红"),
        array("张恨水"),
        array("朱自清"),
        array("张爱玲"),
        array("沈从文"),
        array("徐志摩"),
        array("林徽因"),
        array("田汉"),
        array("夏衍"),
        array("丁玲"),
        array("郁达夫"),
        array("钱钟书"),
        array("李敖"),
        array("琼瑶"),
        array("三毛"),
        array("龙应台"),
        array("王小波"),
        array("莫言"),
        array("贾平凹"),
        array("陈忠实"),
        
        // 艺术体育
        array("达芬奇"),
        array("贝多芬"),
        array("巴赫"),
        array("毕加索"),
        array("米开朗基罗"),
        
        array("王羲之"),
        array("顾恺之"),
        array("阎立本"),
        array("阎立德"),
        array("吴道子"),
        array("欧阳询"),
        array("虞世南"),
        array("颜真卿"),
        array("柳公权"),
        array("张旭"),
        array("怀素"),
        array("李龟年"),
        array("王庭筠"),
        array("徐渭"),
        array("文征明"),
        array("唐伯虎", "normal", "multe-key", "唐伯虎", "唐寅"),
        array("仇英"),
        array("董其昌"),
        array("石涛"),
        array("郑板桥"),
        array("吴昌硕"),
        array("齐白石"),
        array("林怀民"),
        array("吴作人"),
        array("李可染"),
        array("李苦禅"),
        array("弘一法师"),
        array("马一浮"),
        array("启功"),
        
        // 体育
        array("李小龙"),
        array("张国荣"),
        
    ),
    array
    (
        // 工商业人物
        array("古腾堡"),
        array("瓦特"),
        array("莱特兄弟"),
        array("爱迪生"),
        // array("亚历山大·贝尔"),
        array("福特"),
        array("宝马汽车"),
        array("苹果"),
        array("乔布斯"),
        array("盖茨"),
        array("微软"),
        array("Google"),
        array("FaceBook"),
        array("扎克伯格"),
        array("Wiki"),
        array("诺基亚"),
        array("特斯拉"),
        array("马斯克"),
        array("雷军"),
        array("小米"),
        array("任正非"),
        array("华为"),
        array("腾讯"),
        array("马化腾"),
        array("联想"),
        array("支付宝"),
        
    ),
    array
    (
        // 外国政治人物
        array("梭伦"),
        
        array("凯撒"),
        array("亚历山大"),
        array("君士坦丁"),
        array("成吉思汗"),
        array("欧麦尔"),
        array("阿育王"),
        array("哥伦布"),
        array("达·伽马"),
        array("查理曼"),
        array("丰臣秀吉"),
        array("德川家康"),
        array("克伦威尔"),
        array("华盛顿"),
        array("富兰克林"),
        array("杰斐逊"),
        
        array("玻利瓦尔"),
        array("伊莎贝拉一世"),
        array("威廉大帝"),
        array("杰佛逊"),
        array("彼得大帝"),
        array("伊丽莎白女王一世"),
        array("查士丁尼一世"),
        array("丹东"),
        array("罗伯斯比尔"),
        array("拿破仑"),
        array("林肯"),
        array("甘地"),
        array("路德·金"),
        array("罗斯福"),
        array("凯末尔"),
        
        array("列宁"),
        array("斯大林"),
        array("希特勒"),
        array("隆美尔"),
        array("肯尼迪"),
        array("麦克阿瑟"),
        array("杜鲁门"),
        array("尼克松"),
        array("基辛格"),
        array("卡特"),
        array("里根"),
        array("曼德拉"),
        array("胡志明"),
        
        array("克林顿"),
        array("布什"),
        array("希拉里"),
        array("奥巴马"),
        array("拉登"),
        array("金日成"),
        array("金正日"),
        array("金正恩"),
        array("特朗普"),
        array("默克尔"),
        array("朴槿惠"),
    ),
    array
    (
        // array("夏朝", "normal", "tag-time", "中国", "-2070", "-1600"),
        
        // array("商朝", "normal", "tag-time", "中国", "-1600", "-1046"),
        array("商汤", "normal", "key-time", "商汤", "成汤", "-1670", "-1587"),
        array("外丙", "normal", "key-time", "外丙", "-1642", "-1584"),
        array("盘庚", "normal", "key-time", "盘庚", "般庚", "-1300", "-1200"),
        array("小辛", "normal", "key-time", "小辛", "-1200", "-1250"),
        array("小乙", "normal", "key-time", "小乙", "-1251", "-1251"),
        array("武丁", "normal", "key-time", "武丁", "妇好", "-1250", "-1192"),
        array("祖庚", "normal", "key-time", "祖庚", "-1191", "-1191"),
        array("祖甲", "normal", "key-time", "祖甲", "-1190", "-1074"),
        array("廪辛", "normal", "key-time", "廪辛", "-1106", "-1149"),
        array("康丁", "normal", "key-time", "康丁", "-1148", "-1048"),
        array("武乙", "normal", "key-time", "武乙", "-1147", "-1113"),
        array("文丁", "normal", "key-time", "文丁", "-1112", "-1102"),
        array("帝乙", "normal", "key-time", "帝乙", "-1101", "-1076"),
        array("帝辛", "normal", "key-time", "帝辛", "-1075", "-1046"),
        // array("周朝", "super", "tag-time", "中国", "-1046", "-770"),
        // array("春秋战国", "super", "tag-time", "中国", "-770", "-221"),
        // array("秦朝", "normal", "tag-time", "中国", "-221", "-206"),
        
        array("周文王"),
        array("周武王"),
        array("管仲"),
        array("齐桓公"),
        array("宋襄公"),
        array("楚成王"),
        array("晋文公"),
        array("秦穆公"),
        array("楚庄王"),
        array("李悝"),
        array("吴起"),
        array("阖闾"),
        array("夫差"),
        array("勾践"),
        array("孙武"),
        array("伍子胥"),
        array("田忌"),
        array("孙膑"),
        array("魏惠王"),
        array("齐威王"),
        array("庞涓"),
        array("秦孝公"),
        array("燕昭王"),
        array("赵武灵王"),
        array("田单"),
        array("白起"),
        array("范雎"),
        array("秦昭王"),
        array("廉颇"),
        array("王龁"),
        array("赵括"),
        array("信陵君"),
        array("平原君"),
        array("春申君"),
        array("孟尝君"),
        array("吕不韦"),
        array("乐毅"),
        array("张仪"),
        array("公孙衍"),
        array("李冰"),
        array("王翦"),
        array("李牧"),
        array("荆轲"),
        array("太子丹"),
        array("王贲"),
        array("项燕"),
    ),
    array
    (
        // 中国秦汉、魏晋南北朝、隋唐、五代
        array("秦始皇"),
        array("李斯"),
        array("蒙恬"),
        array("赵佗"),
        array("赵高"),
        array("胡亥"),
        array("子婴"),
        array("章邯"),
        array("项羽"),
        array("陈胜吴广", "normal", "multe-key", "陈胜", "吴广"),
        array("刘邦"),
        array("英布"),
        array("张良"),
        array("萧何"),
        array("韩信"),
        array("吕后"),
        array("周勃"),
        array("陈平"),
        array("李广"),
        array("汉文帝"),
        array("汉景帝"),
        array("晁错"),
        array("周亚夫"),
        array("刘濞"),
        array("汉武帝"),
        array("主父偃"),
        array("卫青"),
        array("李陵"),
        array("霍去病"),
        array("董仲舒"),
        array("汉昭帝"),
        array("霍光"),
        array("汉宣帝"),
        array("汉元帝"),
        array("汉成帝"),
        array("桑弘羊"),
        array("王莽"),
        array("冒顿单于"),
        array("张骞"),
        array("张汤"),
        array("光武帝"),
        array("窦固"),
        array("窦宪"),
        array("班超"),
        array("汉明帝"),
        array("邓骘"),
        array("汉顺帝"),
        array("梁冀"),
        array("汉桓帝"),
        array("汉灵帝"),
        array("何进"),
        array("袁绍"),
        array("董卓"),
        array("汉献帝"),
        array("王允"),
        array("吕布"),
        array("李傕"),
        array("郭汜"),
        array("曹操"),
        array("张角"),
        array("孙权"),
        array("刘备"),
        array("刘禅"),
        array("诸葛亮"),
        array("关羽"),
        array("张飞"),
        array("司马昭"),
        array("司马炎"),
        array("张鲁"),
        array("孙坚"),
        array("马腾"),
        array("韩遂"),
        array("刘表"),
        array("孙策"),
        array("袁术"),
        array("公孙瓒"),
        array("周瑜"),
        array("张昭"),
        array("鲁肃"),
        array("魏延"),
        array("张任"),
        array("马超"),
        array("吕蒙"),
        array("李典"),
        array("陆逊"),
        array("司马懿"),
        array("诸葛恪"),
        array("曹丕"),
        array("曹植"),
        array("晋惠帝"),
        array("杨骏"),
        array("贾南风"),
        array("司马玮"),
        array("司马伦"),
        array("司马越"),
        array("司马睿"),
        array("王导"),
        array("谢安"),
        array("谢玄"),
        array("王敦"),
        array("苏峻"),
        array("祖逖"),
        array("桓温"),
        array("慕容垂"),
        array("苻坚"),
        array("桓玄"),
        array("王猛"),
        array("冉闵"),
        array("刘裕"),
        array("宋文帝"),
        array("萧道成"),
        array("萧衍"),
        array("陈霸先"),
        array("苏绰"),
        array("宇文泰"),
        array("独孤信"),
        
        // 隋唐五代
        array("杨坚"),
        array("高颎"),
        array("杨广"),
        array("苏威"),
        array("杨勇"),
        array("杨素"),
        array("宇文化及"),
        array("王薄"),
        array("杨玄感"),
        
        array("李渊"),
        array("李建成"),
        array("李世民"),
        array("李密"),
        array("王世充"),
        array("窦建德"),
        array("房玄龄"),
        array("杜如晦"),
        array("长孙无忌"),
        array("魏徵"),
        array("褚遂良"),
        array("李靖"),
        array("李治"),
        array("武则天"),
        array("狄仁杰"),
        array("张柬之"),
        array("李旦"),
        array("李隆基"),
        array("李林甫"),
        array("杨国忠"),
        array("高仙芝"),
        array("安禄山"),
        array("郭子仪"),
        array("史思明"),
        array("李亨"),
        array("安庆绪"),
        array("史朝义"),
        array("李适"),
        array("李纯"),
        array("李愬"),
        array("黄巢"),
        
        array("李克用"),
        array("李存勗"),
        array("朱温"),
        array("石敬瑭"),
        array("李茂贞"),
        array("郭威"),
        array("马殷"),
        array("朱弘昭"),
        array("孟知祥"),
        array("孟昶"),
        
        // 中国宋辽夏金、元、明、清
        array("赵匡胤"),
        array("赵普"),
        array("范质"),
        array("赵光义"),
        array("潘美"),
        array("寇准"),
        array("范仲淹"),
        array("吕夷简"),
        array("富弼"),
        array("包拯"),
        array("韩琦"),
        array("狄青"),
        array("宋神宗"),
        array("王安石"),
        array("司马光"),
        array("吕惠卿"),
        array("曾布"),
        array("李定"),
        array("蔡京"),
        array("赵煦"),
        array("高太后"),
        array("赵佶"),
        array("方腊"),
        array("韩世忠"),
        array("李纲"),
        array("耶律阿保机"),
        array("梁乙埋"),
        array("梁太后"),
        array("种师道"),
        array("宋高宗"),
        array("秦桧"),
        array("岳飞"),
        array("张浚"),
        array("谢太后"),
        array("张世杰"),
        array("文天祥"),
        array("陆秀夫"),
        array("张弘范"),
        array("札木合"),
        array("王罕"),
        array("铁木真"),
        array("蒙哥"),
        array("窝阔台"),
        array("忽必烈"),
        array("木华黎"),
        array("术赤"),
        array("拖雷"),
        array("拔都"),
        array("阿里不哥"),
        array("察合台"),
        array("旭烈兀"),
        array("贵由"),
        array("马可波罗"),
        
        // 中国明清
        array("刘福通"),
        array("韩林儿"),
        array("郭子兴"),
        array("徐寿辉"),
        array("张士诚"),
        array("陈友谅"),
        array("朱元璋"),
        array("徐达"),
        array("常遇春"),
        array("冯胜"),
        array("傅友德"),
        array("蓝玉"),
        array("汤和"),
        array("刘伯温"),
        // array("朱升"),
        array("胡惟庸"),
        // array("廖永忠"),
        // array("朱亮祖"),
        array("李善长"),
        // array("郭桓"),
        // array("耿炳文"),
        // array("朱标"),
        array("朱允炆"),
        array("齐泰"),
        array("方孝孺"),
        array("黄子澄"),
        array("姚广孝"),
        // array("朱樉"),
        // array("朱㭎"),
        // array("朱权"),
        array("朱棣"),
        // array("亦失哈"),
        array("郑和"),
        // array("陈子鲁"),
        // array("刘大夏"),
        // array("项忠"),
        // array("明仁宗"),
        // array("杨士奇"),
        // array("杨荣"),
        // array("杨溥"),
        array("明宣宗"),
        array("王振"),
        array("也先"),
        array("于谦"),
        /*
        array("明景帝"),
        array("朱见济"),
        array("朱见深"),
        array("万贵妃"),
        array("石亨"),
        array("徐有贞"),
        array("王文"),
        array("曹吉祥"),
        array("李贤"),
        array("汪直"),
        array("梁芳"),
        array("朱祐樘"),
        array("朱厚照"),
        array("刘瑾"),
        array("谷大用"),
        array("朱寘鐇"),
        array("朱宸濠"),
        array("朱厚熜"),
        */
        array("杨廷和"),
        // array("毛澄"),
        // array("张璁"),
        // array("杨金英"),
        array("严嵩"),
        array("严世蕃"),
        array("徐阶"),
        array("俺答"),
        // array("仇鸾"),
        // array("朱纨"),
        // array("张经"),
        array("汪直"),
        array("胡宗宪"),
        array("俞大猷"),
        // array("朱载垕"),
        // array("高拱"),
        array("海瑞"),
        array("张居正"),
        array("冯保"),
        array("顾宪成"),
        array("杨应龙"),
        array("杨涟"),
        array("左光斗"),
        array("朱由校"),
        // array("客氏"),
        array("魏忠贤"),
        array("朱由检"),
        array("袁崇焕"),
        array("李如松"),
        array("孙承宗"),
        array("高第"),
        array("高见"),
        array("赵率教"),
        array("祖大寿"),
        array("熊廷弼"),
        array("满桂"),
        array("李自成"),
        array("张献忠"),
        array("吴三桂"),
        array("朱由崧"),
        array("朱以海"),
        array("朱聿键"),
        array("绍武帝"),
        array("永历帝"),
        array("郑芝龙"),
        array("郑成功"),
        array("史可法"),
        array("张名振"),
        array("张煌言"),
        array("李定国"),
        array("孙可望"),
        array("郝永忠"),
        array("刘体纯"),
        array("刘文秀"),
        array("白文选"),
        array("袁宗弟"),
        array("李来亨"),
        array("王光兴"),
        array("郑经"),
        array("郑克塽"),
        array("左良玉"),
        
        array("努尔哈赤"),
        array("皇太极"),
        array("豪格"),
        array("多铎"),
        array("阿敏"),
        array("莽古尔泰"),
        array("代善"),
        array("多尔衮"),
        array("杨镐"),
        array("林丹汗"),
        array("阿济格"),
        array("范文程"),
        array("孔有德"),
        array("李成梁"),
        array("李成栋"),
        array("洪承畴"),
        array("李国英"),
        array("董学礼"),
        array("王一正"),
        array("施琅"),
        array("耿仲明"),
        array("耿精忠"),
        array("尚可喜"),
        array("尚之信"),
        array("顺治"),
        array("康熙"),
        array("索尼"),
        array("鳌拜"),
        array("于成龙"),
        array("李熙"),
        array("噶尔丹"),
        array("萨布素"),
        array("桑结嘉错"),
        array("雍正"),
        array("隆科多"),
        array("年羹尧"),
        array("乾隆"),
        array("和珅"),
        array("林爽文"),
    ),
    array
    (
        // 中国晚晴民国
        array("嘉庆"),
        array("马戛尔尼"),
        array("道光"),
        array("林则徐"),
        array("魏源"),
        // array("耆英"),
        array("咸丰"),
        
        array("洪秀全"),
        array("石达开"),
        
        // array("杜文秀"),
        // array("马如龙"),
        array("曾国藩"),
        array("左宗棠"),
        array("李鸿章"),
        array("胡林翼"),
        array("曾国荃"),
        array("江忠源"),
        array("罗泽南"),
        array("同治"),
        array("肃顺"),
        array("奕䜣"),
        array("慈禧太后"),
        array("邹容"),
        array("僧格林沁"),
        // array("岑毓英"),
        array("光绪"),
        // array("曾纪泽"),
        array("谭嗣同"),
        // array("康有溥"),
        array("沈葆祯"),
        array("张之洞"),
        array("丁日昌"),
        array("刘坤一"),
        array("奕劻"),
        array("袁世凯"),
        array("载沣"),
        array("宣统"),
        array("溥仪"),
        array("孙中山"),
        array("黄兴"),
        array("蒋介石"),
        array("黎元洪"),
        array("宋教仁"),
        array("胡汉民"),
        array("汪精卫"),
        array("冯玉祥"),
        array("阎锡山"),
        array("张作霖"),
        array("张学良"),
        // array("莫德惠"),
        array("张謇"),
        // array("陈公博"),
        // array("陆皓东"),
        // array("陈少白"),
        array("宋庆龄"),
        array("宋美龄"),
        // array("杨度"),
        array("蔡元培"),
        array("章炳麟"),
        // array("吴敬恒"),
        //array("张继"),
        array("徐锡麟"),
        array("伍廷芳"),
        array("唐绍仪"),
        // array("王宠惠"),
        // array("宋嘉树"),
        array("戴季陶"),
        array("赵秉钧"),
        array("陈其美"),
        array("李烈钧"),
        // array("柏文蔚"),
        // array("谭人凤"),
        array("陈炯明"),
        array("张勋"),
        // array("程璧光"),
        // array("朱庆澜"),
        array("段祺瑞"),
        array("廖仲恺"),
        array("越飞"),
        array("鲍罗廷"),
        array("朱培德"),
        array("谭延恺"),
        array("卢永祥"),
        array("曹锟"),
        // array("头山满"),
        array("熊克武"),
        array("孙科"),
        array("蔡锷"),
        array("唐继尧"),
        array("冯国璋"),
        array("徐世昌"),
        array("许崇智"),
        array("吴佩孚"),
        array("唐生智"),
        array("李宗仁"),
        array("白崇禧"),
        array("陈仪"),
        array("马歇尔"),
        array("胡宗南"),
        array("孙立人"),
        array("张自忠"),
        array("廖耀湘"),
        array("黄百韬"),
        array("黄维"),
        array("杜聿明"),
        array("傅作义"),
        
        array("徐树铮"),
        // array("王揖唐"),
        // array("段芝贵"),
        array("孙传芳"),
        array("陆荣廷"),
        // array("龙济光"),
        // array("顾品珍"),
        // array("张开儒"),
        array("龙云"),
        // array("张怀芝"),
        // array("陈树藩"),
        array("齐燮元"),
        // array("王占元"),
        // array("李纯"),
        // array("陈光远"),
        array("张宗昌"),
        array("郭松龄"),
        array("赵恒惕"),
        // array("陈济棠"),
        // array("刘显世"),
        array("王家烈"),
        array("谭延闿"),
        array("何键"),
        array("刘湘"),
        array("邓锡侯"),
        array("杨森"),
        array("刘文辉"),
        array("韩复榘"),
        // array("刘镇华"),
        array("杨虎城"),
        array("郭坚"),
        // array("党玉琨"),
        array("马鸿宾"),
        array("马鸿逵"),
        array("马麒"),
        array("马麟"),
        array("马步芳"),
        array("马步青"),
        array("马仲英"),
        array("杨增新"),
        array("金树仁"),
        array("盛世才"),
        array("毛泽东", "super", "multe-key", "毛泽东", "毛主席"),
        array("邓小平"),
        array("周恩来", "super", "multe-key", "周恩来", "周总理"),
        array("项英"),
        array("张国焘"),
        array("张闻天"),
        array("李济深"),
        array("张澜"),
        array("高岗"),
        array("林伯渠"),
        array("刘少奇"),
        array("朱德"),
        array("林彪"),
        array("彭德怀"),
        array("刘伯承"),
        array("贺龙"),
        array("陈毅"),
        array("罗荣桓"),
        array("徐向前"),
        array("聂荣臻"),
        array("叶剑英"),
        array("叶挺"),
        array("粟裕"),
        array("徐海东"),
        array("黄克诚"),
        array("陈赓"),
        array("谭政"),
        array("肖劲光"),
        array("张云逸"),
        array("罗瑞卿"),
        array("王树声"),
        array("许光达"),
        array("习仲勋"),
        array("陈云"),
        array("薄一波"),
    ),
    array
    (
        // 中国现代
        array("蒋经国"),
        array("李登辉"),
        array("严家淦"),
        array("马英九"),
        array("连战"),
        array("宋楚瑜"),
        array("陈水扁"),
        array("吴敦义"),
        array("谢长廷"),
        array("蔡英文"),
        
        // array("林立果"),
        array("华国锋"),
        array("胡耀邦"),
        array("赵紫阳"),
        array("江泽民"),
        array("朱镕基"),
        array("胡锦涛"),
        array("温家宝"),
        array("习近平"),
        array("王岐山"),
        array("李克强"),
        
        array("邓力群"),
        array("成思危"),
        array("刘源"),
        array("周小川"),
        array("薄熙来"),
        array("贾庆林"),
        
        array("南方周末"),
        array("程益中"),
        array("喻华峰"),
    ),
    array
    (
        // other
    )
);

?>